my_project:
  outputs:
    dev:
      type: clickhouse
      host: p4i376wb1s.ap-southeast-2.aws.clickhouse.cloud
      port: 8443
      user: default
      password: TN.BR0QPadE62
      # database: db
      schema: default
      secure: true
      threads: 4
  target: dev
